### ISSUE TITLE
Create eCommerce Provider for Faker library

### ISSUE THREAD

**Issue by kloon** [woocommerce/wc-smooth-generator#1]
Currently, we make use of the standard Faker providers when generating data, this data is not really suited for things like product names, categories, tags and attributes.

Implement something along the lines of https://github.com/mbezhanov/faker-provider-collection/blob/master/src/Faker/Provider/Commerce.php which creates a new provider for eCommerce specific functionality to generate more meaningful product data.

**Comment by coreymckrill** [comment]
Closing the loop here. This was implemented in the Products generator a while back, using the third party package suggested above. There are probably other generators that could still make more use of it, but seems like we can close this now.
