### ISSUE TITLE
Installing via Woo plugins will trigger a fatal error

### ISSUE THREAD

**Issue by integrationsbulletproof** [woocommerce/wc-smooth-generator#144]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Once is installed using the WordPress Plugins then will show "Plugin could not be activated because it triggered a fatal error"
![image](https://github.com/user-attachments/assets/b5ba552a-de4f-476c-8ab7-29fe401788ae) , and there is no "fatal error" log created

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://localhost/bulletproof
Site address (URL): https://localhost/bulletproof
WC Version: 9.3.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.2.12
PHP Version: 8.2.12
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 8.4.0
OpenSSL/3.1.3

SUHOSIN Installed: –
MySQL Version: 11.3.2-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.2
WC Database Prefix: wp_
Total Database Size: 31.15MB
Database Data Size: 16.94MB
Database Index Size: 14.21MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.02MB + Index: 0.81MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.48MB + Engine InnoDB
wp_bp_antifraudattempts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bp_antifraudreached: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartbounty: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.22MB + Index: 0.27MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mondula_form_wizards: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.08MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.16MB + Index: 0.25MB + Engine InnoDB
wp_wc_orders_meta: Data: 1.52MB + Index: 5.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.13MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 12
elementor_library: 1
order_status: 1
page: 9
post: 2
product: 5
product_variation: 1
revision: 2
shop_order: 493
shop_order_bp_backup: 13
shop_order_refund: 21
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Query Monitor: by John Blackbourn – 3.16.4
Custom Order Status Manager for WooCommerce: by Bright Plugins – 1.1.3.2
BulletProof Checkout: by BulletProof Checkout  – 1.0.6
BulletProof Checkout Lite: by BulletProof Checkout  – 1.0.7
Code Profiler: by Jerome Bruandet ~ NinTechNet Ltd. – 1.7
Debug Bar: by wordpressdotorg – 1.1.6
Elementor: by Elementor.com – 3.24.4
File Manager Advanced: by modalweb – 5.2.8
Multi Step Form: by Mondula GmbH – 1.7.21
Password Protected Store for WooCommerce: by Geek Code Lab – 2.6.2
Payment and Shipping Method Checkout Fee for WooCommerce: by Ivan Popov – 2.0.1
PHP Compatibility Checker: by WP Engine – 1.6.3
Redis Object Cache: by Till Krüss – 2.5.3
WooCommerce Authorize.Net Gateway: by Pledged Plugins – 6.1.10
CartBounty - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 8.2
WooCommerce Payment Gateway - CCBill: by CCBill – 1.4.1
WooCommerce PayPal Payments: by WooCommerce – 2.9.0
WooCommerce Shipping & Tax: by WooCommerce – 2.8.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.4.4
Extra Product Options & Add-Ons for WooCommerce: by ThemeComplete – 6.4.5
WooCommerce: by Automattic – 9.3.2
WP Debugging: by Andy Fragen – 2.11.24
WP Mail SMTP: by WP Mail SMTP – 4.1.1
WP NMI Gateway PCI for WooCommerce: by Pledged Plugins – 1.2.1

### Inactive Plugins (10) ###

aComposer: by BulletProof Checkout <br@bulletproof-checkout.com> – 0.0.2
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Authorize.Net WooCommerce Lightweight Addon: by Syed Nazrul Hassan – 1.1
BulletProof Website Server IP Address: by BulletProof Checkout – 0.1
GreenPay™ by Green Payment Processing: by Green Payment Processing – 2.2.0
WooCommerce Dummy Payments Gateway: by SomewhereWarm – 1.0.9
WooCommerce Smooth Generator: by Automattic – 1.2.0
WooCommerce Stripe Gateway: by WooCommerce – 8.7.0
WP File Manager: by mndpsingh287 – 8.0
Wp Maximum Upload File Size: by CodePopular – 1.1.1

### Dropin Plugins () ###

object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (1) ###

Code Profiler (mu-plugin): by Jerome Bruandet – 1.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 391 KB

### WC Pages ###

Shop base: #7 - /?page_id=7
Cart: #8 - /?page_id=8 -  This page's content is overridden by custom template content
Checkout: #9 - /?page_id=9 -  This page's content is overridden by custom template content
My account: #10 - /?page_id=10
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-24 15:58:41 +00:00
Options: ✔
Notes: 99
Onboarding: completed

### Action Scheduler ###

Complete: 2,648
Oldest: 2024-08-19 12:12:42 +0000
Newest: 2024-09-23 22:34:43 +0000

Failed: 6
Oldest: 2023-09-13 18:00:27 +0000
Newest: 2024-07-31 16:47:30 +0000

Pending: 7
Oldest: 2024-09-23 22:39:43 +0000
Newest: 2024-09-24 21:08:10 +0000

### Status report information ###

Generated at: 2024-09-23 22:36:14 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce and WooCommerce Smooth Generator plugins are active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
@integrationsbulletproof did you install the code directly from this repo, or did you install the release zip? If you follow the [installation instructions](https://github.com/woocommerce/wc-smooth-generator/blob/trunk/README.md#installation), you shouldn't get an error.

**Comment by integrationsbulletproof** [comment]
Downloaded the code (zip file) from the repo, and installed in Wordpress as any other plugin zip file

**Comment by coreymckrill** [comment]
Is this the zip you downloaded?

https://github.com/woocommerce/wc-smooth-generator/releases/tag/1.2.0

**Comment by integrationsbulletproof** [comment]
no, I downloaded the github code as a zip file, not the released version, the released version worked fine, closing this , thanks
