### ISSUE TITLE
Different problems encountered when generating product categories

### ISSUE THREAD

**Issue by barryhughes** [woocommerce/wc-smooth-generator#153]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I needed to generate a large (though not *that* large) volume of product categories to test a problem. I used:

```
wp wc generate terms product_cat 100
```

On the first attempt, execution stopped a little after the halfway point:

```
Generating terms  65 % [==========================>                   ] 0:06 / 0:09
PHP Fatal error:  Uncaught InvalidArgumentException: minNbChars must be smaller than 
maxNbChars in /.../wp-content/plugins/wc-smooth-generator/vendor/fakerphp/faker/src/
Faker/Provider/Text.php:73
```

On the second attempt, I got a little further then a different error occurred:

```
Generating terms  95 % [============================================>  ] 0:10 / 0:11

PHP Fatal error:  Uncaught OverflowException: Maximum retries of 100 reached without 
finding a valid real text in /.../wp-content/plugins/wc-smooth-generator/vendor/
fakerphp/faker/src/Faker/Provider/Text.php:83
```

Not the same problem, I know. So perhaps these should ideally be separate bug reports, but the common thread was encountering issues when generating 100+ product cats so, provisionally, I've logged this single report. Possibly, these same issues can show up when generating other types of data, too.

### WordPress Environment

- WC 6.7.0-dev
- Smooth Generator 1.2.1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce and WooCommerce Smooth Generator plugins are active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
I just ran into this too. The version of the Faker library was [just updated](https://github.com/woocommerce/wc-smooth-generator/pull/147), so these seem related to that.
