### ISSUE TITLE
Deadlock message when generating products

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/wc-smooth-generator#26]
Got the message below when running 

`wp wc generate products 400`

```
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Deadlock found when trying to get lock; try restarting transaction]<br /><code>
				DELETE FROM `wp_options`
				WHERE `option_name` LIKE (&#039;\_transient\_wc\_uf\_pid\_%&#039;)
				OR `option_name` LIKE (&#039;\_transient\_timeout\_wc\_uf\_pid\_%&#039;)
				OR `option_name` LIKE (&#039;\_transient\_wc\_products\_will\_display\_%&#039;)
				OR `option_name` LIKE (&#039;\_transient\_timeout\_wc\_products\_will\_display\_%&#039;)
```

Please note I was running on branch `update/less-faker-objects` from Friday, IIRC.

Generating actually didn't stop, the message was just written to console.

**Comment by rodrigoprimo** [comment]
Closing as this query will be removed soon likely in the next WC release (see https://github.com/woocommerce/woocommerce/commit/a0e05f972ef28c1f6fa64936f6d4753543846532).

If possible, next time you report a deadlock problem, please include the output of the section `LATEST DETECTED DEADLOCK` from `SHOW ENGINE INNODB STATUS`. This section contains useful information to debug deadlocks, including the last query of the other transaction that caused the problem and a list of the locks held by both transactions.
