### ISSUE TITLE
When I create a variation, it puts post_parent = 0

### ISSUE THREAD

**Issue by davidperezgar** [woocommerce/wc-smooth-generator#38]
Hello,
I'm using this script:
https://github.com/woocommerce/wc-smooth-generator/blob/master/includes/Generator/Product.php
in order to create productos from external API. 

The problem is when I create variations, with the object parent_id, it saves in database post_parent = 0. And I need it.

Any way to solve this?

**Comment by rrennick** [comment]
@davidperezgar WC Smooth Generator is designed to create dummy test data. We aren't looking at adding support for use on live sites.
