### ISSUE TITLE
Dashboard interface doesn't create products and orders

### ISSUE THREAD

**Issue by annq2** [woocommerce/wc-smooth-generator#51]
First of all, thanks for the awesome plugin! It works perfectly via WP CLI commands, but not via admin form. 
I tried locally and on a server.

Notice is appearing, but it doesn't generate any products neither orders.

Cheers!

**Comment by rrennick** [comment]
> but not via admin form.

@annq2 Thanks for reporting. The admin form background processing hasn't been implemented yet.

**Comment by haszari** [comment]
Thanks for reporting @annq2 - I always get confused by this. 

Suggestion - we could add the CLI command reference to the UI, and hide the generator UI until it's fully working. 

Also would be nice to link the plugin row to the UI page and this repo:

<img width="1349" alt="Screen Shot 2021-03-29 at 3 59 23 PM" src="https://user-images.githubusercontent.com/4167300/112781832-2388b780-90a8-11eb-9ea6-7aad21272023.png">

Might be a nice easy good first issue for someone :)

**Comment by rrennick** [comment]
This was addressed in #55.
