### ISSUE TITLE
compatibility with PHP 8

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/wc-smooth-generator#52]
When trying to run `composer install` I get the following error:

>  Problem 1
    - Installation request for fzaninotto/faker v1.8.0 -> satisfiable by fzaninotto/faker[v1.8.0].
    - fzaninotto/faker v1.8.0 requires php ^5.3.3 || ^7.0 -> your PHP version (8.0.0) does not satisfy that requirement.
  Problem 2
    - Installation request for mbezhanov/faker-provider-collection 1.2.1 -> satisfiable by mbezhanov/faker-provider-collection[1.2.1].
    - mbezhanov/faker-provider-collection 1.2.1 requires php ^7.0 -> your PHP version (8.0.0) does not satisfy that requirement.
  Problem 3
    - Installation request for dealerdirect/phpcodesniffer-composer-installer v0.5.0 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0].
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires php ^5.3|^7 -> your PHP version (8.0.0) does not satisfy that requirement.
  Problem 4
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires php ^5.3|^7 -> your PHP version (8.0.0) does not satisfy that requirement.
    - woocommerce/woocommerce-sniffs 0.0.9 requires dealerdirect/phpcodesniffer-composer-installer 0.5.0 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0].
    - Installation request for woocommerce/woocommerce-sniffs 0.0.9 -> satisfiable by woocommerce/woocommerce-sniffs[0.0.9].

**Comment by rrennick** [comment]
@helgatheviking Thanks for reporting the issue.

**Comment by ChrisWiegman** [comment]
@helgatheviking you can get around this for now by appending `-ignore-platform-reqs` to your install command. 

That said, the errors about obsolete packages are still there and can still cause problems if you're running it via a task runner like Make.

**Comment by rrennick** [comment]
Addressed in #56
