### ISSUE TITLE
Add a build script with generated zip being added to release

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/wc-smooth-generator#53]
Do the downloadable release zip files need to be compiled/built? Are the release zip files expected to run as is or do they still need to be compiled/built with composer?

>Warning: require(/public_html/wp-content/plugins/wc-smooth-generator-1.0.2/vendor/autoload.php): failed to open stream: No such file or directory in /public_html/wp-content/plugins/wc-smooth-generator-1.0.2/wc-smooth-generator.php on line 17

**Comment by rrennick** [comment]
@helgatheviking The release zips are just the Github default zip of the repo. We need to add a build script. I'll edit the title of this issue and put it on the enhancement list.

**Comment by helgatheviking** [comment]
Thanks Ron! I will keep an eye on that as that's something I've been meaning to learn myself.
