### ISSUE TITLE
Use more realistic product categories

### ISSUE THREAD

**Issue by haszari** [woocommerce/wc-smooth-generator#54]
It looks like smooth generator uses a list of real "products" when generating - e.g. hat, glove, knife etc.

The categories look like they are more randomly generated lorem-ipsum style text (e.g. `est, nesciunt, numquam, quia, repellendus`.

It would be cool if the the product type was used for categories also, e.g. all hats in a `Hats` category, for example:

<img width="1024" alt="Screen Shot 2021-04-12 at 9 20 08 AM" src="https://user-images.githubusercontent.com/4167300/114321720-48812e00-9b70-11eb-88f8-1058be8d6e79.png">

Could also add categories for the other words used in the product name, e.g. the second "material" word - `Leather`, `Concrete`, `Wooden` etc.

Using consistent categories like this would make it easier to test different scenarios involving product categories, as the expected category would be more intuitive.

**Comment by ovidiul** [comment]
As I find this useful as well, I am proposing this PR https://github.com/woocommerce/wc-smooth-generator/pull/65 which makes use of the words from the product name and adds them to the terms(`product_tag`, `product_tag`) along with the `$faker->department` generated name from https://github.com/mbezhanov/faker-provider-collection
