### ISSUE TITLE
Create a permanent archive URL

### ISSUE THREAD

**Issue by rrennick** [woocommerce/wc-smooth-generator#61]
Each time we release a new version the link to the archive changes. We should add a permanent location for the latest zip similar to a nightly build.

**Comment by coreymckrill** [comment]
It seems like GitHub maybe already [handles this](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases)?

This seems to work to download the latest zip file:
https://github.com/woocommerce/wc-smooth-generator/releases/latest/download/wc-smooth-generator.zip
