### ISSUE TITLE
Only Generate Orders to countries that we sell to

### ISSUE THREAD

**Issue by hedqvist** [woocommerce/wc-smooth-generator#66]
Since there is a setting in WooCommerce, the plugin should perhaps respect this when generating orders.

Option for reference: woocommerce_allowed_countries

or WC_Countries::get_allowed_countries()

**Comment by rrennick** [comment]
@hedqvist Thanks for the suggestion. I've added it to the feature requests list.

**Comment by coreymckrill** [comment]
This one will be easier to address once we do #131
