### ISSUE TITLE
'generate' is not a registered subcommand of 'wc.

### ISSUE THREAD

**Issue by prasidhda** [woocommerce/wc-smooth-generator#7]
I am not able the "generate" command. Checked into the https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Commands , don't see any generate command. 

Can you help here?

**Comment by kloon** [comment]
It is there https://github.com/woocommerce/wc-smooth-generator/blob/master/includes/CLI.php#L103

Make sure you have the plugin activated before running the command, you will also need to have WooCommerce installed and activated.

**Comment by prasidhda** [comment]
Thanks.
It was my stupidity to check without activating the plugin itself.
